'use strict';
const assert=require('assert');
const fs=require('fs');
const core=require('../src/codex-safe-core/quality-platform');
const pkg=require('../package.json');
const policy=fs.readFileSync('src/policy.js','utf8');
const codex=fs.readFileSync('src/codex.js','utf8');
const quality=fs.readFileSync('src/quality.js','utf8');
const extension=fs.readFileSync('extension.js','utf8');
const semanticEvidence=fs.readFileSync('src/semantic-evidence.js','utf8');
const semanticReview=fs.readFileSync('src/semantic-review.js','utf8');
assert.deepStrictEqual(core.REVIEW_PROFILE_NAMES,['quick','standard','deep','security','embedded']);
assert.strictEqual(pkg.contributes.configuration.properties['safeCodexReview.profile'].default,'standard');
assert.ok(pkg.contributes.commands.some(x=>x.command==='safeCodexReview.importSarif'));
assert.ok(pkg.contributes.commands.some(x=>x.command==='safeCodexReview.generateFix'));
assert.ok(!pkg.contributes.commands.some(x=>x.command==='safeCodexReview.independentReviewStaged'));
assert.match(extension,/createReplayWindow/);
assert.ok(!pkg.contributes.commands.some(x=>x.command==='safeCodexReview.forceReviewStaged'));
assert.match(policy,/resolveReviewProfile/); assert.match(policy,/sarifFiles/);
assert.match(codex,/hypothesisSchema/); assert.match(codex,/verificationSchema/); assert.match(codex,/runCodexPatchProposal/); assert.match(codex,/deterministicSummary/);
assert.match(quality,/normalizeSarif/); assert.match(quality,/validatePatchProposal/);
assert.match(semanticEvidence,/git\(\['show'/); assert.match(semanticEvidence,/grep','--cached/); assert.match(semanticReview,/insufficient_evidence/); assert.match(semanticReview,/contradicted/);
assert.doesNotMatch(quality,/execSync|spawnSync|child_process/);
assert.match(extension,/importSarifEvidence/); assert.match(extension,/generateFixProposal/); assert.doesNotMatch(extension,/independentReviewStaged|forceReviewStaged/); assert.match(extension,/resolveFinding/); assert.match(extension,/showTextDocument/);
console.log('Review Quality Platform adapter tests passed.');
