'use strict';
const assert=require('assert');
const fs=require('fs');
const core=require('../src/codex-safe-core/quality-platform');
const pkg=require('../package.json');
const policy=fs.readFileSync('src/policy.js','utf8');
const codex=fs.readFileSync('src/codex.js','utf8');
const quality=fs.readFileSync('src/quality.js','utf8');
const extension=fs.readFileSync('extension.js','utf8');
assert.deepStrictEqual(core.REVIEW_PROFILE_NAMES,['quick','standard','deep','security','embedded']);
assert.strictEqual(pkg.contributes.configuration.properties['safeCodexReview.profile'].default,'standard');
assert.ok(pkg.contributes.commands.some(x=>x.command==='safeCodexReview.importSarif'));
assert.ok(pkg.contributes.commands.some(x=>x.command==='safeCodexReview.generateFix'));
assert.match(policy,/resolveReviewProfile/); assert.match(policy,/sarifFiles/);
assert.match(codex,/formatAnalyzerEvidence/); assert.match(codex,/runCodexPatchProposal/); assert.match(codex,/deterministicSummary/);
assert.match(quality,/buildImpactEvidenceGraph/); assert.match(quality,/normalizeSarif/); assert.match(quality,/validatePatchProposal/);
assert.doesNotMatch(quality,/execSync|spawnSync|child_process/);
assert.match(extension,/importSarifEvidence/); assert.match(extension,/generateFixProposal/); assert.match(extension,/showTextDocument/);
console.log('Review Quality Platform adapter tests passed.');
