#!/usr/bin/env python3
import json, pathlib
root=pathlib.Path('.')
CORE="c59a036cdb0b5839fe0e794031d38fd274bc116b"
OLD="a4a8acab6565bdb7e5f7927d2a4db14d31a6e895"
def read(p): return (root/p).read_text()
def write(p,s): (root/p).write_text(s)
def loadj(p): return json.loads(read(p))
def savej(p,v): write(p,json.dumps(v,ensure_ascii=False,indent=2)+"\n")

for p,zh in [("package.nls.json",False),("package.nls.zh-cn.json",True)]:
    d=loadj(p)
    d["command.importSarif.title"]="导入 SARIF 审查证据" if zh else "Import SARIF Evidence"
    d["command.generateFix.title"]="生成安全修复候选" if zh else "Generate Safe Fix Proposal"
    d["config.profile"]="Review 执行 Profile；只在现有安全/预算上限内调整证据深度。" if zh else "Review execution profile; adjusts evidence depth only within existing safety and budget caps."
    labels={"quick":"快速、最小证据","standard":"标准平衡","deep":"深度影响分析","security":"安全优先","embedded":"嵌入式/并发/资源优先"} if zh else {"quick":"Quick minimal evidence","standard":"Balanced standard review","deep":"Deep impact analysis","security":"Security-focused review","embedded":"Embedded/concurrency/resource-focused review"}
    for n,v in labels.items(): d[f"config.profile.{n}"]=v
    d["config.sarifFiles"]="仓库内由用户或 CI 预先生成的 SARIF 文件；扩展不会执行 analyzer 命令。" if zh else "Repository-relative SARIF files pre-generated by the user or CI; the extension never executes analyzer commands."
    savej(p,d)

tr={
"SARIF evidence imported: {0} findings.":"已导入 SARIF 证据：{0} 个 findings。",
"Select a SARIF file generated by your analyzer or CI":"选择由 analyzer 或 CI 预先生成的 SARIF 文件",
"No completed review with actionable findings is available.":"当前没有包含可操作 findings 的已完成审查。",
"Select a finding to generate a fix proposal":"选择要生成修复候选的 finding",
"Codex is generating a bounded fix proposal…":"Codex 正在生成有界修复候选…",
"Previewed patch proposal touches {0}. Apply it to the working tree?":"修复候选将修改 {0}。是否应用到 working tree？",
"Apply Fix":"应用修复",
"Patch applied to the working tree. Inspect it, stage the intended changes, then re-review.":"补丁已应用到 working tree。请检查并 Stage 需要的修改，然后重新审查。",
"Re-review":"重新审查",
"The reviewed staged snapshot changed. Generate the fix again from a current review.":"已审查的 staged snapshot 已变化。请基于最新审查重新生成修复。",
"Configured SARIF evidence could not be loaded: {0}":"无法加载已配置的 SARIF 证据：{0}"
}
for p in ["l10n/bundle.l10n.json","l10n/bundle.l10n.zh-cn.json"]:
    d=loadj(p); zh=p.endswith("zh-cn.json")
    for k,v in tr.items(): d[k]=v if zh else k
    savej(p,d)

for p in [".codex-safe.example.json",".github/workflows/family-release-guard.yml","scripts/release.test.js"]:
    s=read(p)
    if OLD not in s: raise SystemExit(f"old Core SHA missing: {p}")
    write(p,s.replace(OLD,CORE))

s=read("scripts/build.js")
s=s.replace("'review.js', 'report.js', 'receipts.js', 'codex.js'","'review.js', 'report.js', 'receipts.js', 'codex.js', 'quality.js'")
s=s.replace("'git-repository.js', 'context-builder.js', 'efficiency-planner.js', 'policy.js', 'review-rules.js'","'git-repository.js', 'context-builder.js', 'efficiency-planner.js', 'quality-platform.js', 'policy.js', 'review-rules.js'")
write("scripts/build.js",s)

s=read("scripts/verify-module-boundaries.js")
s=s.replace("'efficiency-planner.js','policy.js','review-rules.js','core-contract.json'","'efficiency-planner.js','quality-platform.js','policy.js','review-rules.js','core-contract.json'")
s=s.replace("Safe Core v4.3 runtime missing","Safe Core v4.4 runtime missing")
s=s.replace("for (const modulePath of ['./src/i18n', './src/review-support', './src/process', './src/git', './src/policy', './src/review', './src/report', './src/receipts', './src/codex'])","for (const modulePath of ['./src/i18n', './src/review-support', './src/process', './src/git', './src/policy', './src/review', './src/report', './src/receipts', './src/codex', './src/quality'])")
s=s.replace("assert.match(codexModule, /efficiency-planner/, 'Review token/risk budgeting must delegate to Core');","assert.match(codexModule, /efficiency-planner/, 'Review token/risk budgeting must delegate to Core');\nassert.match(codexModule, /quality-platform/, 'Review profile/analyzer/patch validation must delegate to Core');")
s=s.replace("Codex Safe Core v4.3 with cost-aware planning","Codex Safe Core v4.4 with quality/impact planning")
write("scripts/verify-module-boundaries.js",s)

s=read("src/policy.js")
s=s.replace("const { fingerprintPolicy } = require('./codex-safe-core/safe-contract');","const { fingerprintPolicy } = require('./codex-safe-core/safe-contract');\nconst { resolveReviewProfile } = require('./codex-safe-core/quality-platform');")
marker="  if (model.length > 128 || /[\\r\\n\\0]/.test(model)) throw new Error(t('User-level safeCodexReview.model is invalid.'));\n"
insert=marker+"\n  const profile = resolveReviewProfile(String(getUserOnlySetting(config, 'profile', 'standard') || 'standard'));\n  const sarifRaw = getUserOnlySetting(config, 'sarifFiles', []);\n  if (!Array.isArray(sarifRaw) || sarifRaw.length > 8 || sarifRaw.some(value => typeof value !== 'string' || !value.trim() || value.length > 512 || /[\\r\\n\\0]/.test(value))) throw new Error('User-level safeCodexReview.sarifFiles is invalid.');\n  const sarifFiles = Object.freeze(sarifRaw.map(value => value.trim()));\n"
if marker not in s: raise SystemExit("policy marker missing")
s=s.replace(marker,insert,1)
s=s.replace("    model,\n    language,","    model,\n    profile: profile.name,\n    profileConfig: profile,\n    sarifFiles,\n    repoRoot,\n    language,",1)
s=s.replace("    projectPolicyFingerprint: options.projectPolicyFingerprint\n","    projectPolicyFingerprint: options.projectPolicyFingerprint,\n    reviewProfile: options.profile,\n    sarifEvidenceEnabled: options.sarifFiles.length > 0\n",1)
write("src/policy.js",s)

s=read("src/review.js")
s=s.replace("? 'Write summary, title, description, and suggestion in English.'\n    : 'Write summary, title, description, and suggestion in Simplified Chinese; keep severity, category, and file in the schema-defined values.';","? 'Write finding title, description, and suggestion in English.'\n    : 'Write finding title, description, and suggestion in Simplified Chinese; keep severity, category, and file in the schema-defined values.';")
s=s.replace("'- Return an empty findings array when there is no substantive issue.',","'- Return an empty findings array when there is no substantive issue.',\n    '- Set summary to an empty string. The controller generates the final summary deterministically from validated findings.',")
write("src/review.js",s)

s=read("extension.js")
s=s.replace("  runCodexReview,\n  isCliCompatibilityError","  runCodexReview,\n  runCodexPatchProposal,\n  isCliCompatibilityError")
s=s.replace("} = require('./src/codex');\n","} = require('./src/codex');\nconst { collectImpactEvidence, loadSarifFiles, importSarifFile, applyValidatedPatch } = require('./src/quality');\n",1)
s=s.replace("const gitInvalidationTimers = new Map();","const gitInvalidationTimers = new Map();\nconst importedSarifByRepo = new Map();\nconst lastReviewsByRepo = new Map();")
old="        const review = await runCodexReview(diff, stagedPaths, options, token);\n        return { review, snapshot: snapshotAfter, changedLineRanges, stagedChangeMetadata, binaryPathSet, submodulePathSet, stagedPolicyChange, diffFingerprint, diffBytes, options };"
new="        const impact = await collectImpactEvidence(repoRoot, diff, options.profileConfig, token);\n        let configuredSarif = [];\n        try { configuredSarif = loadSarifFiles(repoRoot, options.sarifFiles); }\n        catch (error) { log(t('Configured SARIF evidence could not be loaded: {0}', error?.message || error)); }\n        const analyzerFindings = [...configuredSarif, ...(importedSarifByRepo.get(key) || [])];\n        const review = await runCodexReview(diff, stagedPaths, options, token, { impact, analyzerFindings });\n        return { review, snapshot: snapshotAfter, changedLineRanges, stagedChangeMetadata, binaryPathSet, submodulePathSet, stagedPolicyChange, diffFingerprint, diffBytes, diff, options };"
if old not in s: raise SystemExit("review call marker missing")
s=s.replace(old,new,1)
marker="    reviewSnapshotsByRepo.set(normalizeFsPath(repoRoot), result.snapshot);\n"
s=s.replace(marker,marker+"    lastReviewsByRepo.set(normalizeFsPath(repoRoot), { repoRoot, review: result.review, options: result.options, snapshot: result.snapshot, stagedPaths: [...result.stagedChangeMetadata.keys()], diff: result.diff });\n",1)
insert="""async function importSarifEvidence(commandArgs = []) {
  assertTrustedWorkspace();
  const repositoryInfo = await chooseRepository(commandArgs); if (!repositoryInfo) return;
  const repoRoot = repositoryInfo.root, key = normalizeFsPath(repoRoot);
  const picked = await vscode.window.showOpenDialog({ canSelectMany: false, defaultUri: vscode.Uri.file(repoRoot), filters: { SARIF: ['sarif','json'] }, openLabel: t('Select a SARIF file generated by your analyzer or CI') });
  if (!picked?.[0]) return;
  const findings = importSarifFile(repoRoot, picked[0].fsPath);
  importedSarifByRepo.set(key, findings);
  vscode.window.showInformationMessage(t('SARIF evidence imported: {0} findings.', findings.length));
}

async function generateFixProposal(commandArgs = []) {
  assertTrustedWorkspace();
  const repositoryInfo = await chooseRepository(commandArgs); if (!repositoryInfo) return;
  const repoRoot = repositoryInfo.root, key = normalizeFsPath(repoRoot), last = lastReviewsByRepo.get(key);
  if (!last?.review?.findings?.length) { vscode.window.showInformationMessage(t('No completed review with actionable findings is available.')); return; }
  const current = await getRepositorySnapshot(repoRoot);
  if (!snapshotsEqual(current, last.snapshot)) { vscode.window.showWarningMessage(t('The reviewed staged snapshot changed. Generate the fix again from a current review.')); return; }
  const items = last.review.findings.map(finding => ({ label: `[${finding.severity.toUpperCase()}] ${finding.title}`, description: `${finding.file}:${finding.line}`, finding }));
  const selected = await vscode.window.showQuickPick(items, { placeHolder: t('Select a finding to generate a fix proposal') }); if (!selected) return;
  const proposal = await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title: t('Codex is generating a bounded fix proposal…'), cancellable: true }, async (_progress, token) => runCodexPatchProposal(last.diff,last.stagedPaths,last.options,selected.finding,token));
  const document = await vscode.workspace.openTextDocument({ language: 'diff', content: proposal.patch });
  await vscode.window.showTextDocument(document, { preview: true });
  const applyAction=t('Apply Fix');
  const choice=await vscode.window.showWarningMessage(t('Previewed patch proposal touches {0}. Apply it to the working tree?', proposal.touchedPaths.join(', ')), { modal: true }, applyAction);
  if (choice !== applyAction) return;
  const beforeApply=await getRepositorySnapshot(repoRoot);
  if (!snapshotsEqual(beforeApply,last.snapshot)) { vscode.window.showWarningMessage(t('The reviewed staged snapshot changed. Generate the fix again from a current review.')); return; }
  await applyValidatedPatch(repoRoot,proposal,last.stagedPaths);
  const reReview=t('Re-review');
  const next=await vscode.window.showInformationMessage(t('Patch applied to the working tree. Inspect it, stage the intended changes, then re-review.'),reReview);
  if(next===reReview) await vscode.commands.executeCommand('safeCodexReview.reviewStaged');
}

"""
marker="async function clearReview() {"
if marker not in s: raise SystemExit("clear marker missing")
s=s.replace(marker,insert+marker,1)
s=s.replace("  reportsByRepo.clear();","  reportsByRepo.clear();\n  importedSarifByRepo.clear();\n  lastReviewsByRepo.clear();",1)
reg="    vscode.commands.registerCommand('safeCodexReview.showOutput', () => outputChannel.show(true)),\n"
extra="    vscode.commands.registerCommand('safeCodexReview.importSarif', async (...args) => { try { await importSarifEvidence(args); } catch (error) { vscode.window.showErrorMessage(t('Codex Review Safe failed: {0}', friendlyError(error))); } }),\n    vscode.commands.registerCommand('safeCodexReview.generateFix', async (...args) => { try { await generateFixProposal(args); } catch (error) { vscode.window.showErrorMessage(t('Codex Review Safe failed: {0}', friendlyError(error))); } }),\n"
if reg not in s: raise SystemExit("registration marker missing")
s=s.replace(reg,reg+extra,1)
write("extension.js",s)

s=read("scripts/verify-security-manifest.js")
s=s.replace("requireTrustedWhen(paletteItems, 'safeCodexReview.checkEnvironment');","requireTrustedWhen(paletteItems, 'safeCodexReview.checkEnvironment');\nrequireTrustedWhen(paletteItems, 'safeCodexReview.importSarif');\nrequireTrustedWhen(paletteItems, 'safeCodexReview.generateFix');")
s=s.replace("assert.match(source, /async function checkEnvironment","assert.match(source, /async function importSarifEvidence\\([^)]*\\)\\s*\\{\\s*assertTrustedWorkspace\\(\\);/, 'importSarifEvidence must enforce Workspace Trust first');\nassert.match(source, /async function generateFixProposal\\([^)]*\\)\\s*\\{\\s*assertTrustedWorkspace\\(\\);/, 'generateFixProposal must enforce Workspace Trust first');\nassert.match(source, /async function checkEnvironment")
write("scripts/verify-security-manifest.js",s)

s=read("CHANGELOG.md")
if "## 4.1.0 - 2026-08-27" not in s:
    s=s.replace("## Unreleased\n","## Unreleased\n\n## 4.1.0 - 2026-08-27\n\n- Adopt Safe Core 4.4 Quality Platform with user review profiles, bounded local Impact Evidence, pre-generated SARIF evidence, deterministic controller summaries and explicit preview-before-apply fix proposals.\n- Keep Safe Contract v2, Policy Schema v3, Review Receipt v4, exact changed-line publication and Workspace Trust unchanged.\n",1)
write("CHANGELOG.md",s)
